[build]
  publish = "."

[[redirects]]
  from = "/api/catalog"
  to = "/data/catalog.json"
  status = 200

[[redirects]]
  from = "/api/army/:id"
  to = "/data/armies/:id.json"
  status = 200

[[redirects]]
  from = "/army-builder"
  to = "/army-builder/"
  status = 301

[[redirects]]
  from = "/"
  to = "/army-builder/"
  status = 302
  force = true
  conditions = {Host = ["vf-army-builder.denlockhart.com"]}
